### ISSUE TITLE
How to use this module

### ISSUE THREAD

**Issue by redorav** [akaStiX/premake-vsandroid#1]
Hi akaStiX,

I've stumbled across your premake module but I can't seem to be able to generate an Android packaging solution. I constantly get "unsupported kind Packaging used for project" ...

Any chance you could share some sample configuration to get started? I'm not an expert on premake although I love the system.

Your library seems the most promising of all the ones I've found since it tries to create a native VS solution instead of going through gmake or custom builds.

Thanks!

**Comment by akaStiX** [comment]
@redorav you can find the premake scripts I use to build my own project here:
https://bitbucket.org/StiX/stix-engine/src/3882697025c1fa13ccd885a6c489539933867eaf/premake5.lua?at=master&fileviewer=file-view-default
https://bitbucket.org/StiX/stix-engine/src/3882697025c1fa13ccd885a6c489539933867eaf/Premake/Engine/premake5.lua?at=master&fileviewer=file-view-default

**Comment by redorav** [comment]
Thank you very much!

I didn't realize you actually need a separate solution to generate Android projects. Can it not be generated as an additional platform in the same solution?

**Comment by akaStiX** [comment]
Frankly speaking I don't remember the reason, why I had to go with a separate solution. It must be possible to have android as a target architecture withing the same solution, but there were some obstacles.
Plus MSBuild for VS-android had a lot of problems and bugs, when I was writing this plug-in. And I haven't seen them fixed even in the latest update to VS 2015, released a week ago.

**Comment by redorav** [comment]
Thanks for your reply. Could you elaborate a bit on what problems and bugs are present that are stopping and /or annoying you? Basically I need to support an Android solution for projects and I'm undecided as whether to support the new MSBuild alternative or go with something different.

**Comment by akaStiX** [comment]
This is what I've sent to MS:

> 1. There are no way to select different toolchain besides Clang 3.6 and GCC 4.9.
> 2. There are no way to build application for architectures different than ARMv7A - MIPS, ARM64, etc. However it looks like I can change this through hidden attributes. I am not that well familiar with MSBuild, but in Android schema it has a few invisible attributes that refer to architecture and toolchain. I haven’t tried that yet.
> 3. When you try to link against shared standard library, you’ll get this:
>    2>C:\Program Files (x86)\MSBuild\Microsoft\MDD\Android\V140\Android.Common.targets(240,5): error MSB3030: Could not copy the file "C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\thumb\libgnustl_shared.a" because it was not found.
>    Note, that it tries to link against *.a file, which is a static lib.
> 4. No multi core compilation option.
> 5. Would be nice, if this one https://connect.microsoft.com/VisualStudio/feedback/details/1031464/compiling-ndk-project-when-including-cmath-causes-issues-with-clang-and-libc could be ACTUALLY fixed. Since every new starter will have to Google for the solution. https://code.google.com/p/android/issues/detail?id=79890&thanks=79890&ts=1416335194
> 6. When you add libraries to Additional Command Line options for linker, they are not linked. It looks like this options are appended to the command line and LD is sensitive to the parameters order, so those libs are not linked. But if you add them to input dependencies they’ll link. This is a problem, when you want to use linker groups -( and -) or --start-group and --end-group
> 7. If "Output Directory" and "Intermediate Directory" (project properties -> general) are different, MSBuild will silently launch binary that strips the *.so, this build step from Android.Common.targets:310 is the one to blame:
>    
>    <Exec Condition="'$(PackageDebugSymbols)' != 'true' and '$(LinkSkippedExecution)' != 'true' and '$(TargetPath)' != $([System.IO.Path]::GetFullPath('$(LinkOutputFile)'))" Command="$(StripToolExe) $(StripOptions) -o &quot;$(TargetPath)&quot; &quot;$(LinkOutputFile)&quot;" />
>    I am not sure whether this is a right thing to do, but I've spend a lot of hours trying to find out, why my app was crashing on startup and some symbols were missing, so I couldn't debug what happens. It turned out, that android_main was stripped from the shared library on this step and I've found that only by a lucky accident.
> 8. When switch the Hex view (on\off) multiple times VS can hang. Here is MSBuild ticket - https://github.com/Microsoft/MIEngine/issues/69
> 9. Watch window cannot take the address of the method. Could be a GDB issue.
> 10. High CPU usage by VS in clr.dll!LogHelp_TerminateOnAssert when AndroidManifest.xml is not located in the same folder with corresponding *.androidproj
> 11. const char\* error = Error::GetLastErrorMessage(); generates compiler error with Clang.

It was a year ago and I did not followup on what they actually have in their latest update, but as I've said before - I've seen nothing in their release notes regarding Android support. It's possible, that I missed something. MS told me, that they fixed some of the issues back in the days. And I don't have time at the moment to dig into current situation with Android support. The biggest stopper was a lack of linker groups support in the toolchain (7th paragraph in the list). It'll be pretty painful to live without it, if you have a project with multiple libs

**Comment by akaStiX** [comment]
@redorav I am looking at the latest Android plugin (Update 3) for VS 2015 and it has fixed some of the issues I've described in my previous post - at least number 2 and 4 is fixed, 5 seems to be fixed as well. Probably there is more, but I have to check it yet

**Comment by redorav** [comment]
That looks very nice. I ended up going with the NVIDIA Nsight Tegra plugin as it seems to have very good support from NVIDIA and has support for many flavors of VS as well. I will come back to this though as it seems like MS is doing a lot of progress on it lately.
