### ISSUE TITLE
Errors from latest premake version

### ISSUE THREAD

**Issue by andr3wmac** [akaStiX/premake-vsandroid#2]
There are two errors produced by running this module in the latest version of premake (5.0.0 alpha 10).

1) Error: ../vsandroid/_preload.lua:226: name 'symbolspath' in use
2) Error: ../vsandroid/vsandroid_packaging.lua:127: attempt to index field 'sectionmap' (a nil value)

**Comment by akaStiX** [comment]
Yes, I know that. This is an easy to fix, however it depends on my project - it uses an older modified premake version. Before I'll port my premake changes to newer version you'll have to stick to previous version or fix it yourself. ETA for this fix is ~2-3 days

**Comment by akaStiX** [comment]
Fixed in 6885216a698729071584157d1da04f6f432030da
